name: Deploy to Dev Instance
on:
  workflow_dispatch:
    inputs:
      pr_branch:
        description: "PR Branch"
        required: true
      instance:
        description: "Instance of IB2 that we want to deploy to"
        required: true

jobs:
  GetData:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4

      - name: Get PR information
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            const prBranch = '${{ github.event.inputs.pr_branch }}';
            const command = `git fetch origin ${prBranch} && git checkout ${prBranch}`;
            try {
              const result = execSync(command, { encoding: 'utf8' });
              console.log('Checkout result:', result);
            } catch (error) {
              console.error('Checkout error:', error);
              throw error;
            }

      - name: Show Gathered Data
        shell: bash
        run: |
          echo "PR Number: ${{ github.event.inputs.pr_number }}"
          echo "Comment ID: ${{ github.event.inputs.comment_id }}"
          echo "PR SHA: ${{ github.event.inputs.pr_sha }}"
          echo "PR Branch: ${{ github.event.inputs.pr_branch }}"
          echo "Instance: ${{ github.event.inputs.instance }}"