name: Deploy to Dev Instance
on:
  workflow_dispatch:
    inputs:
      pr_branch:
        description: "PR Branch"
        required: true
      instance:
        description: "Instance of IB2 that we want to deploy to"
        required: true

jobs:
  validate:
    name: Validating Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          if ! [[ "${{ github.event.inputs.pr_branch }}" =~ (?i)^(feature|bugfix|techdebt)/.* ]]; then
            echo "::error::Invalid branch name. Must start with feature/, bugfix/, or techdebt/"
            exit 1
          fi

  GetData:
    name: Build Docker Image for instance - ${{ github.event.inputs.instance }}
    needs: validate
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.pr_branch }}

      - name: Show Gathered Data
        shell: bash
        env:
          INSTANCE: ${{ github.event.inputs.instance }}
        run: |
          echo "Current branch name: $(git branch --show-current)"
          echo "Full branch info: $(git status)"
          echo "Recent commits: $(git log -3 --oneline)"
          echo "Instance: $INSTANCE"
          if [[ "$INSTANCE" == "salesSupport" ]]; then 
            echo "THIS IS salesSupport"
          elif [[ "$INSTANCE" == "fiji" ]]; then
            echo "THIS IS fiji"
          else
            echo "THIS IS default IO"
          fi